server:
  port: 8082
  context-path: /publisher
endpoints:
  actuator:
    enabled: true
    sensitive: false
  configprops:
    sensitive: false
  beans:
    sensitive: false
  env:
    sensitive: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/Users/paula/Documents/dev/h2/pub;MODE=MYSQL;IGNORECASE=TRUE;
    data-username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  activemq:
    broker-url: tcp://localhost:61616
flyway:
  baseline-version: 0
  enabled: true
  out-of-order: false
  locations: db/migration
